In [4]:
# load library
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# create a learning data
X = np.array([[0, 2.10, 1.45],
[1, 1.18, 1.33],
[0, 1.22, 1.27],
[1, -0.21, -1.19]])

# create a need to be predicted data
X_with_nan = np.array([[np.nan, 0.87, 1.31],
[np.nan, -0.67, -0.22]])

# Train Knn learner
clf = KNeighborsClassifier(3, weights="distance")
trained_model = clf.fit(X[:,1:], X[:,0])

# Predict missing value
imputed_values = trained_model.predict(X_with_nan[:,1:])

# Join column
X_with_imputed = np.hstack((imputed_values.reshape(-1, 1), X_with_nan[:, 1:]))
X_with_imputed 

full_features = np.vstack((X, X_with_imputed ))
full_features

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19],
       [ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22]])

#### POP OUT !!!!
------

In [2]:
print("Full dataset with imputed values:\n", full_features)

Full dataset with imputed values:
 [[ 0.    2.1   1.45]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.21 -1.19]
 [ 0.    0.87  1.31]
 [ 1.   -0.67 -0.22]]


In [5]:
# Evaluate accuracy of imputation (if true labels are available)
# True labels for X_with_nan: [0, 1]
true_labels = np.array([0, 1])
imputed_accuracy = accuracy_score(true_labels, imputed_values)
print("\nImputed Accuracy:", imputed_accuracy)


Imputed Accuracy: 1.0
